version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-Develop
    env_file:
      - .env
    environment:
      - TZ=Asia/Bangkok
    volumes:
     - './:/app'  # ใช้ volume ที่เชื่อมต่อไฟล์ในเครื่องกับ Docker
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge